### ISSUE TITLE
Contribute to Flycheck?

### ISSUE THREAD

**Issue by swsnr** [themattchan/flycheck-liquidhs.el#1]
Hey, would you like to contribute this to Flycheck itself, to add out-of-the-box Liquid support?

**Comment by themattchan** [comment]
Yes, that would be nice -- how do I go about doing that?

**Comment by swsnr** [comment]
@themattchan Oh, well, you could open a pull request, but really you don't need to do anything.  I can easily copy the syntax checker definition to Flycheck myself :relaxed:  I just needed your permission :blush:

**Comment by themattchan** [comment]
That would be even better! Please do it! :)

**Comment by cpitclaudel** [comment]
I think this is fine as a separate package, so I've closed the corresponding issue on the Flycheck side.
