### ISSUE TITLE
Update the ucsd-progsys fork

### ISSUE THREAD

**Issue by bandali** [themattchan/flycheck-liquidhs.el#6]
Please pull the latest changes from this repo into `ucsd-progsys/flycheck-liquidhs.el` so that MELPA would pick it up.

Also, please enable the issue trackers for `ucsd-progsys/flycheck-liquidhs.el` and `ucsd-progsys/liquid-types.el`.

**Comment by bandali** [comment]
@themattchan Any news on this?

**Comment by themattchan** [comment]
I don't have access to the ucsd-progsys org, will ping @ranjitjhala again...

**Comment by ranjitjhala** [comment]
I can give you access if you like? Would that be easiest?

**Comment by themattchan** [comment]
@ranjitjhala sure!

**Comment by ranjitjhala** [comment]
@themattchan I just have you access can you confirm?

**Comment by themattchan** [comment]
@ranjitjhala got it

**Comment by SohumB** [comment]
Hi! Just to note, I got bitten by #4 and was very confused until I realised I'd gotten an older version from melpa :)

**Comment by bandali** [comment]
Same here (that's why I opened this issue). It'd be great if @themattchan could pull the changes into the fork now that he has access.

**Comment by themattchan** [comment]
ok, finally fixed.
